import { Product, Category } from './types';

export const ALL_PRODUCTS: Product[] = [
  {
    id: 0,
    full: '真大心PLUS住院醫療健康保險附約（外溢型）',
    color: '#009A4E',
    ph: '500–3,000元',
    min: 500,
    max: 3000,
    fakeBase: 3840,
    ratios: {
      daily: 1,
      icu: 2,
      discharge: 0.5,
      home: 0.4,
      transfer: 15,
      early: 25,
      first: 100,
      heavy: 50,
      specific: 150,
      low: 10,
      care: 2.5,
      chemo: 15,
      radio: 15,
      target: 25,
      marrow: 100,
      chemorad: 1.5,
      hospice: 1,
      surgery: 25,
      opd: 0.25,
      prepost: 0.25,
      er: 0.75,
    },
  },
  {
    id: 1,
    full: '心安PLUS手術醫療定期健康保險附約（外溢型）',
    color: '#1D9E75',
    ph: '500–2,000元',
    min: 500,
    max: 2000,
    fakeBase: 2560,
    ratios: {
      daily: 1,
      icu: 1.5,
      discharge: 0.5,
      home: null,
      transfer: 15,
      early: 15,
      first: 100,
      heavy: 40,
      specific: null,
      low: 10,
      care: 2,
      chemo: 12,
      radio: 15,
      target: null,
      marrow: 75,
      chemorad: 1.5,
      hospice: 0.75,
      surgery: 20,
      opd: 0.2,
      prepost: 0.2,
      er: 0.75,
    },
  },
  {
    id: 2,
    full: '樂順心手術醫療定期健康保險（外溢型）',
    color: '#D85A30',
    ph: '500–3,000元',
    min: 500,
    max: 3000,
    fakeBase: 2140,
    ratios: {
      daily: 1,
      icu: null,
      discharge: 0.5,
      home: 0.25,
      transfer: 15,
      early: null,
      first: 100,
      heavy: 30,
      specific: 100,
      low: null,
      care: 1.5,
      chemo: 10,
      radio: 15,
      target: 20,
      marrow: null,
      chemorad: 1.5,
      hospice: null,
      surgery: 15,
      opd: null,
      prepost: 0.15,
      er: 0.75,
    },
  },
];

export const CATEGORIES: Category[] = [
  { key: 'hospital', label: '住院', keys: ['daily', 'icu', 'discharge', 'home', 'transfer'] },
  { key: 'cancer', label: '癌症保障', keys: ['early', 'first', 'heavy', 'specific', 'low', 'care'] },
  { key: 'treatment', label: '治療項目', keys: ['chemo', 'radio', 'target', 'marrow', 'chemorad', 'hospice'] },
  { key: 'outpatient', label: '門急診', keys: ['surgery', 'opd', 'prepost', 'er'] },
];

export const KEY_LABELS: Record<string, string> = {
  daily: '住院日額保險金',
  icu: '每日加護病房',
  discharge: '出院療養金',
  home: '在家療養金',
  transfer: '緊急醫療轉送',
  early: '初期或輕度癌症保險金',
  first: '初次罹癌',
  heavy: '重度癌症保險金',
  specific: '初次罹患特定癌症',
  low: '低侵襲性癌症保險金',
  care: '癌症照護保險金',
  chemo: '化學治療',
  radio: '放射線醫療',
  target: '標靶治療',
  marrow: '骨髓移植',
  chemorad: '化療或放療',
  hospice: '安寧療護',
  surgery: '癌症住院手術',
  opd: '門診保險金',
  prepost: '住院前後門診',
  er: '急診保險金',
};

export const KEY_UNITS: Record<string, string> = {
  daily: '/日',
  icu: '/日',
  discharge: '/日',
  home: '/日',
  transfer: '/次',
  early: '/次',
  first: '/次',
  heavy: '/次',
  specific: '/次',
  low: '/次',
  care: '/月',
  chemo: '/次',
  radio: '/次',
  target: '/次',
  marrow: '/次',
  chemorad: '/日',
  hospice: '/日',
  surgery: '/次',
  opd: '/次',
  prepost: '/次',
  er: '/次',
};

export const TAB_NAMES = ['商品一', '商品二', '商品三'];
